### PR TITLE
Support multiple storage backends

### LINKED ISSUE #2: Plaintext serialization
I used BSON when I first wrote this package because it was just way easier than anything else, but storing unreadable binary files in Git repos is annoying. It would be nice to support YAML and JSON.

### LINKED ISSUE #5: Move CI from Travis to GitHub Actions?
cc: @christopher-dG

### PR DESCRIPTION
**Pull request by christopher-dG**
Closes #5
Closes #2 

This works, but I need to write tests and probably some docs. Tomorrow maybe.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Any particular reason for making YAML the default, instead of JSON?

**Comment by christopher-dG** [comment]
YAML's multiline strings are 500x easier to read (they actually go on multiple lines).

**Comment by DilumAluthge** [comment]
> YAML's multiline strings are 500x easier to read (they actually go on multiple lines).

Sounds like a very good reason!

**Comment by christopher-dG** [comment]
I kinda forgot about this but I should be able to take care of the rest on Monday.

**Comment by christopher-dG** [comment]
This still desperately needs docs but I think I'm planning to write a blog post about this and a few other testing packages, so I'll save it for then.

**Pull request merged**
